name: build
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Download Go modules
              run: go mod download

            - name: Get gocover-cobertura
              run: |
                  go install github.com/boumenot/gocover-cobertura@latest

            - name: Run Test
              run: |
                  go test ./... -coverprofile=coverage.txt
                  gocover-cobertura < coverage.txt > coverage.xml

            - name: Code Coverage Summary
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: coverage.xml
                  format: markdown
                  badge: true
