name: build
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Coverage Summary
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: coverage/**/coverage.cobertura.xml
                  format: markdown
                  badge: true
